###############################################################################
# This compose definition starts up a self contained slaclab elogbook instance
###############################################################################

version: '3.1'

services:

  ###
  # we finally have the web portal for the logbook
  ###
  runparams:
    image: slaclab/logbook-runparams
    ports:
      - 5000:5000
    environment:
      - LOGBOOK_AUTHDB_DEFAULT_HOST=mysql
      - LOGBOOK_AUTHDB_DEFAULT_USER=cryoem_u
      # - LOGBOOK_AUTHDB_DEFAULT_PASSWORD=<PASSWORD>
      - LOGBOOK_EXPTIMEMON_DEFAULT_HOST=mysql
      - LOGBOOK_EXPTIMEMON_DEFAULT_USER=cryoem_u
      # - LOGBOOK_EXPTIMEMON_DEFAULT_PASSWORD=<PASSWORD>
      # - LOGBOOK_FILEMGR_ICWS_MONITORING_PASSWORD=<PASSWORD>
      - LOGBOOK_FILEMGR_ICWS_MONITORING_USER=cryoem_u
      # - LOGBOOK_FILEMGR_ICWS_PASSWORD=<PASSWORD>
      - LOGBOOK_FILEMGR_ICWS_USER=cryoem_u
      # - LOGBOOK_FILEMGR_ICWS_STANDARD_PASSWORD=<PASSWORD>
      - LOGBOOK_FILEMGR_ICWS_STANDARD_USER=cryoem_u
      # - LOGBOOK_FILEMGR_IRODSWS_PASSWORD=<PASSWORD>
      - LOGBOOK_ICAT_DEFAULT_HOST=mysql
      - LOGBOOK_ICAT_DEFAULT_USER=cryoem_u
      # - LOGBOOK_ICAT_DEFAULT_PASSWORD=<PASSWORD>
      - LOGBOOK_IFACECTRL_STANDARD_DEFAULT_USER=cryoem_u
      # - LOGBOOK_IFACECTRL_STANDARD_DEFAULT_PASSWORD=<PASSWORD>
      - LOGBOOK_IFACECTRL_DEFAULT_USER=cryoem_u
      # - LOGBOOK_IFACECTRL_DEFAULT_PASSWORD=<PASSWORD>
      - LOGBOOK_IFACECTRL_MONITORING_DEFAULT_USER=cryoem_u
      # - LOGBOOK_IFACECTRL_MONITORING_DEFAULT_PASSWORD=<PASSWORD>
      - LOGBOOK_IREP_DEFAULT_HOST=mysql
      - LOGBOOK_IREP_DEFAULT_USER=cryoem_u
      # - LOGBOOK_IREP_DEFAULT_PASSWORD=<PASSWORD>
      - LOGBOOK_LOGBOOK_DEFAULT_HOST=mysql
      - LOGBOOK_LOGBOOK_DEFAULT_USER=cryoem_u
      # - LOGBOOK_LOGBOOK_DEFAULT_PASSWORD=<PASSWORD>
      - LOGBOOK_LOGGER_DEFAULT_HOST=mysql
      - LOGBOOK_LOGGER_DEFAULT_USER=cryoem_u
      # - LOGBOOK_LOGGER_DEFAULT_PASSWORD=<PASSWORD>
      - LOGBOOK_NEOCAPTAR_DEFAULT_HOST=mysql
      - LOGBOOK_NEOCAPTAR_DEFAULT_USER=cryoem_u
      # - LOGBOOK_NEOCAPTAR_DEFAULT_PASSWORD=<PASSWORD>
      - LOGBOOK_PORTAL_DEFAULT_HOST=mysql
      - LOGBOOK_PORTAL_DEFAULT_USER=cryoem_u
      # - LOGBOOK_PORTAL_DEFAULT_PASSWORD=<PASSWORD>
      - LOGBOOK_REGDB_DEFAULT_HOST=mysql
      - LOGBOOK_REGDB_DEFAULT_LDAP_HOST=ldaps://ldap603.slac.stanford.edu
      - LOGBOOK_REGDB_DEFAULT_USER=cryoem_u
      # - LOGBOOK_REGDB_DEFAULT_PASSWORD=<PASSWORD>
      - LOGBOOK_SHIFTMGR_DEFAULT_HOST=mysql
      - LOGBOOK_SHIFTMGR_DEFAULT_USER=cryoem_u
      # - LOGBOOK_SHIFTMGR_DEFAULT_PASSWORD=<PASSWORD>
      - LOGBOOK_SYSMON_DEFAULT_HOST=mysql
      - LOGBOOK_SYSMON_DEFAULT_USER=cryoem_u
      # - LOGBOOK_SYSMON_DEFAULT_PASSWORD=<PASSWORD>
      - LOGBOOK_IMAGESTORE_MASTER=http://thumbnail-master:9333
    secrets:
      - LOGBOOK_AUTHDB_DEFAULT_PASSWORD
      - LOGBOOK_EXPTIMEMON_DEFAULT_PASSWORD
      - LOGBOOK_FILEMGR_ICWS_MONITORING_PASSWORD
      - LOGBOOK_FILEMGR_ICWS_PASSWORD
      - LOGBOOK_FILEMGR_ICWS_STANDARD_PASSWORD
      - LOGBOOK_FILEMGR_IRODSWS_PASSWORD
      - LOGBOOK_ICAT_DEFAULT_PASSWORD
      - LOGBOOK_IFACECTRL_STANDARD_DEFAULT_PASSWORD
      - LOGBOOK_IFACECTRL_DEFAULT_PASSWORD
      - LOGBOOK_IFACECTRL_MONITORING_DEFAULT_PASSWORD
      - LOGBOOK_IREP_DEFAULT_PASSWORD
      - LOGBOOK_LOGBOOK_DEFAULT_PASSWORD
      - LOGBOOK_LOGGER_DEFAULT_PASSWORD
      - LOGBOOK_NEOCAPTAR_DEFAULT_PASSWORD
      - LOGBOOK_PORTAL_DEFAULT_PASSWORD
      - LOGBOOK_REGDB_DEFAULT_PASSWORD
      - LOGBOOK_SHIFTMGR_DEFAULT_PASSWORD
      - LOGBOOK_SYSMON_DEFAULT_PASSWORD


secrets:
  LOGBOOK_AUTHDB_DEFAULT_PASSWORD:
    external: true
  LOGBOOK_EXPTIMEMON_DEFAULT_PASSWORD:
    external: true
  LOGBOOK_FILEMGR_ICWS_MONITORING_PASSWORD:
    external: true
  LOGBOOK_FILEMGR_ICWS_PASSWORD:
    external: true
  LOGBOOK_FILEMGR_ICWS_STANDARD_PASSWORD:
    external: true
  LOGBOOK_FILEMGR_IRODSWS_PASSWORD:
    external: true
  LOGBOOK_ICAT_DEFAULT_PASSWORD:
    external: true
  LOGBOOK_IFACECTRL_STANDARD_DEFAULT_PASSWORD:
    external: true
  LOGBOOK_IFACECTRL_DEFAULT_PASSWORD:
    external: true
  LOGBOOK_IFACECTRL_MONITORING_DEFAULT_PASSWORD:
    external: true
  LOGBOOK_IREP_DEFAULT_PASSWORD:
    external: true
  LOGBOOK_LOGBOOK_DEFAULT_PASSWORD:
    external: true
  LOGBOOK_LOGGER_DEFAULT_PASSWORD:
    external: true
  LOGBOOK_NEOCAPTAR_DEFAULT_PASSWORD:
    external: true
  LOGBOOK_PORTAL_DEFAULT_PASSWORD:
    external: true
  LOGBOOK_REGDB_DEFAULT_PASSWORD:
    external: true
  LOGBOOK_SHIFTMGR_DEFAULT_PASSWORD:
    external: true
  LOGBOOK_SYSMON_DEFAULT_PASSWORD:
    external: true
